fix boost 1.64.0 odeint integrate bug
Fix error `boost/numeric/ublas/matrix.hpp(5977): error: namespace "boost::serialization" has no member "make_array"`.
This bug is introduced with boost 1.64.0.
boost issue [12516](https://svn.boost.org/trac/boost/ticket/12516).